language: node_js
node_js:
  - 'node'
deploy:
  on:
    tags: true
  provider: npm
  email: 'lesmo@lesmo.com.mx'
  api_key: '${NPM_TOKEN}'
  skip_cleanup: true
  edge: true # https://travis-ci.community/t/missing-api-key-when-deploying-to-github-releases/5761/14